import papers from '../data/papers.json';
import trials from '../data/trials.json';
import topics from '../data/topics.json';
import methods from '../data/methods.json';
import atlas from '../data/atlas.json';
import news from '../data/news.json';
import team from '../data/team.json';
import translations from '../data/en/content.json';
const ep=translations.papers as Record<string,string[]>;
const ef=translations.figures as Record<string,string[][]>;
const et=translations.topics as Record<string,string[]>;
const em=translations.methods as unknown as Record<string,[string,string,string[][]]>;
const ea=translations.atlas as Record<string,string[]>;
const en=translations.news as Record<string,string[]>;
const e=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const u=(p='')=>`${import.meta.env.BASE_URL.replace(/\/$/,'')}/en/${p}`;
const a=(path:string,label:string,cls='text-link')=>`<a class="${cls}" href="${u(path)}">${label}</a>`;
const ext=(url:string,label:string)=>`<a class="source-link" href="${e(url)}" target="_blank" rel="noreferrer">${e(label)} ↗</a>`;
const badge=(v:string)=>`<span class="badge">${e(v)}</span>`;
const systems:Record<string,string>={human:'Human',animal:'Animal',exvivo:'Ex vivo',model:'Computational model',review:'Review / consensus'};
const relevance:Record<string,string>={direct:'Directly related',supporting:'Supporting evidence',context:'Background'};
const endpoints:Record<string,string>={'发作簇控制':'Seizure-cluster control','持续状态控制':'Status epilepticus control','长期发作控制':'Long-term seizure control'};
const status:Record<string,string>={TERMINATED:'Study terminated early',COMPLETED:'Completed',RECRUITING:'Recruiting'};
const trialIntro:Record<string,[string,string]>={
 NCT01390220:['ARTEMIS-1 · cluster rescue','Outpatient seizure-cluster rescue: cessation within 10 minutes and no recurrence from 10 minutes through 6 hours after dosing. The primary endpoint also accounts for additional open-label dosing.'],
 NCT01960075:['ESETT · status epilepticus','Second-line treatment after benzodiazepines: clinical cessation and improved consciousness within 60 minutes of infusion start, without additional anticonvulsants. Registry enrollment and published analysis populations must be distinguished.'],
 NCT04391569:['RAISE · intravenous ganaxolone','Clinical/EEG cessation within 30 minutes, no escalation to intravenous anesthesia within 36 hours, and treatment-emergent adverse events are listed separately as primary outcomes.'],
 NCT06344338:['tDCS · refractory status','Targeted versus sham tDCS for status termination. The registered primary time frame is through study completion, an average of 1 year; it must not be rewritten as a minute-scale acute cessation rate.'],
 NCT04839601:['RESPONSE · responsive stimulation','Background evidence: serious device-related adverse events through 84 days and a seizure-reduction response at 12 months. This is not an individual-seizure interruption endpoint.']
};
const refs=(ids:string[])=>`<div class="reference-list">${ids.map(id=>{const p=papers.find(x=>x.id===id)!;return a(`library/${id}/`,`${e(p.titleOriginal)}<span>${p.year} · PMID ${id} ↗</span>`,'reference-row')}).join('')}</div>`;
const head=(tag:string,title:string,desc:string,extra='')=>`<section class="container inner-hero"><p class="eyebrow">${tag}</p><h1>${e(title)}</h1><p class="lead">${e(desc)}</p>${extra}</section>`;
const crumbs=(path:string,label:string)=>`<div class="container breadcrumbs">${a('','Home','')}<span>/</span>${a(path,label,'')}<span>/</span><span>Current page</span></div>`;
const prose=(html:string)=>`<article class="container prose narrow">${html}</article>`;
const section=(title:string,text:string)=>`<section><h2>${e(title)}</h2><p>${e(text)}</p></section>`;
const tile=(path:string,title:string,desc:string,tone:string,wide='')=>`<a class="portal-card ${tone} ${wide}" href="${u(path)}"><span class="portal-arrow" aria-hidden="true">↗</span><div><h2>${e(title)}</h2><p>${e(desc)}</p></div></a>`;
const tones=['portal-cream','portal-sand','portal-peach','portal-sage','portal-stone','portal-apricot'];
const categoryNav=()=>`<nav class="subnav" aria-label="Evidence sections">${[['evidence/','Overview'],['library/','Literature'],['trials/','Trials'],['methods/','Methods'],['resources/','Resources']].map(([p,t])=>a(p,t,'')).join('')}</nav>`;
const select=(name:string,label:string,opts:[string,string][])=>`<label>${label}<select name="${name}"><option value="">All</option>${opts.map(([v,t])=>`<option value="${e(v)}">${e(t)}</option>`).join('')}</select></label>`;
const unique=(v:string[])=>[...new Set(v)];
const form=(kind:string,filters:string)=>`<form class="filters" role="search" data-filter-form data-kind="${kind}"><label class="search-field">${kind==='papers'?'Search literature':'Search registered studies'}<input name="q" type="search" placeholder="${kind==='papers'?'Title, author, PMID or DOI':'Title, keyword or registry ID'}" autocomplete="off"/></label><div class="filter-selects">${filters}<label>Sort<select name="sort"><option value="new">Newest first</option><option value="old">Oldest first</option></select></label><button class="reset" type="reset">Clear filters ↺</button></div><p class="result-count" aria-live="polite"></p></form>`;
function paperCard(p:typeof papers[number]){return `<article class="paper-card result-card" data-search="${e([p.titleOriginal,p.titleZh,...p.authors,p.pmid,p.doi,...ep[p.id]].join(' ').toLowerCase())}" data-system="${p.studySystems.join(' ')}" data-topic="${p.topicIds.join(' ')}" data-year="${p.year}" data-type="${e(p.design)}" data-relevance="${p.relevanceTier}"><div class="paper-meta"><span>${p.year} / ${e(p.journal)}</span><span>${p.studySystems.map(s=>badge(systems[s])).join('')}</span></div><h3>${a(`library/${p.id}/`,e(p.titleOriginal),'')}</h3><p>${e(ep[p.id][2])}</p><div class="paper-foot"><span>${badge(relevance[p.relevanceTier])} ${badge(ef[p.id]?'Full-text notes':'Abstract summary')}</span>${a(`library/${p.id}/`,'Read notes ↗','')}</div></article>`;}
function trialCard(t:typeof trials[number]){return `<article class="trial-card result-card" data-search="${e([t.id,t.briefTitle,...trialIntro[t.id]].join(' ').toLowerCase())}" data-status="${t.statusRaw}" data-endpoint="${e(t.endpointCategory)}" data-relevance="${t.relevanceTier}" data-country="${e(t.countries.join('|'))}" data-type="${t.studyType}" data-year="${t.registryLastUpdatedAt}"><div class="paper-meta"><span>${t.id}</span>${badge(status[t.statusRaw]||t.statusRaw)}</div><h3>${a(`trials/${t.slug}/`,e(trialIntro[t.id][0]),'')}</h3><p>${e(trialIntro[t.id][1])}</p><div class="paper-foot">${badge(endpoints[t.endpointCategory])}<span>Verified ${t.verifiedAt}</span>${a(`trials/${t.slug}/`,'View record ↗','')}</div></article>`;}
export const englishPages:{path:string,title:string,description:string,html:string}[]=[];
const add=(path:string,title:string,description:string,html:string)=>englishPages.push({path:'en'+(path?'/'+path:''),title,description,html});
add('','Home','Seizure Termination: mechanisms, human recordings, clinical research and recovery.',`<section class="portal-heading"><h1>Seizure Termination</h1><p>Connecting human electrophysiology, mechanisms and clinical research.</p></section><nav class="portal-grid" aria-label="Main sections">${tile('about/','About termination','Concepts, research milestones and postictal recovery.',tones[0])}${tile('news/','Research news','Recent findings and their original sources.',tones[1])}${tile('work/','Our work','Human SEEG, published foundations and research directions.',tones[2],'portal-wide')}${tile('research/','Research areas','Phenotypes, infraslow activity, networks and mechanisms.',tones[3])}${tile('evidence/','Literature & trials','Animal and clinical literature, registered studies and methods.',tones[4])}${tile('atlas/','Termination atlas','Explore different offset patterns using teaching simulations.',tones[5],'portal-wide')}</nav>`);
add('evidence','Literature & trials','Choose literature, registered studies, methods or resources.',head('LITERATURE & REGISTERED STUDIES','Literature & trials','Choose a category, then search the collection or open a detailed record.')+`<nav class="portal-grid portal-subgrid" aria-label="Evidence categories">${tile('library/','Research literature',`${papers.length} selected papers across human, animal, ex vivo and computational systems.`,tones[0])}${tile('trials/','Registered studies',`${trials.length} verified records: design, status, outcomes and results.`,tones[2])}${tile('methods/','Research methods','Annotation, slow-potential processing and statistical validation.',tones[3])}${tile('resources/','Resources','Official literature and registry platforms.',tones[4])}</nav>`);
add('research','Research areas','Six areas connecting termination and recovery.',head('RESEARCH LANDSCAPE','Research areas','Choose an area to explore its questions, evidence and related literature.')+`<section class="container section compact"><div class="topic-grid">${topics.map(t=>`<a class="topic-card tone-${t.index}" href="${u(`research/${t.id}/`)}"><span class="card-top">${t.index} / RESEARCH <span>↗</span></span><h3>${et[t.id][0]}</h3><p>${et[t.id][1]}</p></a>`).join('')}</div></section>`);
for(const t of topics){const x=et[t.id];add(`research/${t.id}`,x[0],x[1],crumbs('research/','Research areas')+head(`${t.index} / RESEARCH`,x[0],x[1])+`<div class="container reading-layout"><article class="prose">${section(x[2],x[3])}<h2>Evidence and open questions</h2><div class="callout">${x[4]}</div><h2>Reading starts here</h2>${refs(t.paperIds)}${section('How to investigate further','Start with explicit observational definitions. Distinguish recorded phenomena, model interpretations and intervention tests. Report the experimental system, analytical window and independent validation scope.')} ${a(t.id==='recovery'?'framework/3r/':'methods/',t.id==='recovery'?'Explore the 3R framework ↗':'Methods and validation ↗')}</article><aside class="reading-aside"><p class="eyebrow">EXPLORE FURTHER</p>${topics.filter(y=>y.id!==t.id).map(y=>a(`research/${y.id}/`,et[y.id][0],'aside-link')).join('')}</aside></div>`);}
add('library','Literature','Search human, animal, ex vivo, computational and review evidence.',head('EVIDENCE LIBRARY','Literature and research evidence','Search by system, question and relevance. This curated collection is not a systematic review.',categoryNav())+`<section class="container section compact">${form('papers',select('system','System',Object.entries(systems))+select('topic','Topic',topics.map(t=>[t.id,et[t.id][0]]))+select('year','Year',unique(papers.map(p=>p.year)).sort().reverse().map(y=>[y,y]))+select('type','Study design',unique(papers.map(p=>p.design)).map(d=>[d,ep[papers.find(p=>p.design===d)!.id][0]]))+select('relevance','Relevance',Object.entries(relevance)))}<div class="result-list">${[...papers].sort((a,b)=>b.year.localeCompare(a.year)).map(paperCard).join('')}</div><p class="empty-state" hidden>No matching papers. Try fewer filters or another keyword.</p></section>`);
for(const p of papers){const x=ep[p.id],figs=ef[p.id];add(`library/${p.id}`,p.titleOriginal,x[1],crumbs('library/','Literature')+head(`LITERATURE / ${p.year}`,p.titleOriginal,x[1],`<div class="tag-row">${p.studySystems.map(s=>badge(systems[s])).join('')}${badge(relevance[p.relevanceTier])}${badge(figs?'Full-text notes':'Abstract summary')}</div>`)+`<div class="container reading-layout"><article class="prose"><section><h2>01 / Bibliographic information</h2><p>${e(p.authors.join(', '))}</p><p><strong>${e(p.journal)}</strong> · ${p.year} · ${e(p.volume)} · ${e(p.pages)}</p>${ext(p.url,`PubMed · ${p.id}`)}${p.doi?ext('https://doi.org/'+p.doi,'DOI · '+p.doi):''}${p.pmcid?ext('https://pmc.ncbi.nlm.nih.gov/articles/'+p.pmcid+'/','PMC full text'):''}<p class="small">Published record · ${x[0]} · Verified ${p.verifiedAt}</p></section>${section('02 / Research logic',x[1]+' '+x[2])}${section('03 / Mechanism and methods',x[0]+'. '+x[3])}<section><h2>04 / ${figs?'Main figures and tables':'Source access'}</h2>${figs?`<p class="small">Notes based on the main text and main figure/table descriptions. Original figures are not reproduced. Independent supplements have not all been verified.</p><div class="figure-list">${figs.map((f,i)=>{const label=(p as {figures?:{label:string}[]}).figures?.[i]?.label.replace('图','Figure').replace('表','Table')||`Figure ${i+1}`;return `<details><summary><span>${label}</span> ${e(f[0])}</summary><p><strong>Design and observation:</strong> ${e(f[1])}</p><p><strong>Interpretive limits:</strong> ${e(f[2])}</p>${ext(`https://pmc.ncbi.nlm.nih.gov/articles/${p.pmcid}/`,'Open original figures')}</details>`}).join('')}</div>`:'<p>This record summarizes the verified abstract. Complete main text and supplementary materials have not been verified; no figure-by-figure analysis is provided.</p>'}</section>${section('05 / Evidence synthesis',x[2])}<p>Related topics: ${p.topicIds.map(id=>a(`research/${id}/`,et[id][0])).join(' · ')}</p>${section('06 / Critical appraisal',x[3])}${p.relatedTrialIds.length?`<h2>Linked registered studies</h2>${p.relatedTrialIds.map(id=>trialCard(trials.find(t=>t.id===id)!)).join('')}`:''}</article><aside class="reading-aside"><p class="eyebrow">READING NOTES</p><h3>Keep evidence within its study conditions.</h3><p>${x[0]}</p><p>Source scope: ${figs?'main text and main figure/table descriptions':'verified PubMed abstract'}.</p>${a('about/evidence-policy/','Evidence policy ↗')}<hr/><h3>Related literature</h3>${refs(papers.filter(q=>q.id!==p.id&&q.topicIds.some(id=>p.topicIds.includes(id))).slice(0,3).map(q=>q.id))}</aside></div>`);}
add('trials','Registered studies','Distinguish status, endpoints, time windows and posted results.',head('CLINICAL STUDY REGISTRY','Registered studies','Directly related trials and long-term-control background studies are labeled separately. Status is not efficacy.',categoryNav())+`<section class="container section compact">${form('trials',select('status','Status',unique(trials.map(t=>t.statusRaw)).map(s=>[s,status[s]||s]))+select('endpoint','Endpoint',Object.entries(endpoints))+select('relevance','Relevance',Object.entries(relevance))+select('country','Country',unique(trials.flatMap(t=>t.countries)).map(c=>[c,c]))+select('type','Study type',unique(trials.map(t=>t.studyType)).map(s=>[s,s])))}<div class="result-list">${trials.map(trialCard).join('')}</div><p class="empty-state" hidden>No matching registered studies.</p><div class="callout small">This curated collection contains verified ClinicalTrials.gov records. Chinese registry and WHO coverage remains limited; this is not a complete trial list. Each record retains registry-update and verification dates.</div></section>`);
const date=(d:{date:string,type?:string}|null)=>d?`${e(d.date)} · ${d.type==='ACTUAL'?'Actual':d.type==='ESTIMATED'?'Estimated':'Type not reported'}`:'Not reported';
const facts=(rows:[string,unknown][])=>`<dl class="facts">${rows.map(([k,v])=>`<dt>${e(k)}</dt><dd>${e(v)}</dd>`).join('')}</dl>`;
for(const t of trials)add(`trials/${t.slug}`,trialIntro[t.id][0],trialIntro[t.id][1],crumbs('trials/','Registered studies')+head(`REGISTERED STUDY / ${t.id}`,trialIntro[t.id][0],t.briefTitle,`<div class="tag-row">${badge(status[t.statusRaw]||t.statusRaw)}${badge(endpoints[t.endpointCategory])}${badge(relevance[t.relevanceTier])}</div>`)+`<div class="container reading-layout"><article class="prose"><div class="callout"><strong>Relationship to seizure termination</strong><p>${trialIntro[t.id][1]}</p></div><h2>Study design</h2>${facts([['Official title',t.officialTitle],['Sponsor',t.sponsor],['Type / phase',t.studyType+' / '+t.phase.join(' / ')],['Design',Object.values(t.design).filter(v=>typeof v==='string').join(' · ')],['Age',t.populationSummary.replace('未报告上限','upper limit not reported')],['Enrollment',`${t.enrollment.count} · ${t.enrollment.type==='ACTUAL'?'Actual':'Estimated'} enrollment (registry population)`],['Countries',t.countries.join(', ')||'Not reported']])}<h2>Interventions and comparators</h2>${t.interventions.map(i=>`<div class="compact-block"><strong>${e(i.name)}</strong> <span class="small">${e(i.type)}</span></div>`).join('')}<p class="small">Research information only; no individual dosing or stimulation advice is provided.</p><h2>Primary outcomes and time frames</h2><p>The original registry fields are retained to preserve complete composite endpoints.</p>${t.primaryOutcomes.map((o,i)=>`<section class="outcome"><p class="eyebrow">OUTCOME ${i+1}</p><h3>${e(o.measure)}</h3>${'description' in o?`<p>${e(o.description)}</p>`:''}<p><strong>Time frame:</strong> ${e(o.timeFrame)}</p></section>`).join('')}<h2>Status and results</h2>${facts([['Official status',`${status[t.statusRaw]||t.statusRaw} / ${t.statusRaw}`],['Why stopped',t.whyStopped||'Not reported / not applicable'],['Registry results',t.resultsPosted?'Results posted':'No results posted'],['Start',date(t.startDate)],['Primary completion',date(t.primaryCompletionDate)],['Completion',date(t.completionDate)]])}${t.statusRaw==='TERMINATED'?'<div class="callout">Study termination is an operational trial status. It does not mean successful seizure termination and does not by itself establish lack of efficacy or safety.</div>':''}<h2>Linked publications</h2>${t.relatedPaperIds.length?refs(t.relatedPaperIds):'<p class="small">No formal results paper linked to this registry ID has been verified here. References listed in a registry are not automatically results of that trial.</p>'}</article><aside class="reading-aside"><p class="eyebrow">REGISTRY SNAPSHOT</p><h3>${t.id}</h3><p>Registry updated: ${t.registryLastUpdatedAt}</p><p>Verified: ${t.verifiedAt}</p><p>Check the official record and study center for current recruitment.</p>${ext(t.canonicalUrl,'Official registry record')}<hr/>${a('trials/','Back to registered studies ←')}</aside></div>`);
add('atlas','Termination atlas','Teaching simulations of spatial and terminal activity patterns.',head('SEIZURE OFFSET ATLAS','Termination atlas','Compare spatial termination order and terminal activity independently. All current examples are original teaching simulations.')+`<section class="container section compact"><div class="atlas-grid">${atlas.map((t,i)=>`<a class="atlas-card" href="${u(`atlas/${t.id}/`)}"><span class="eyebrow">EXAMPLE 0${i+1} / ${badge('Simulation')}</span><div class="mini-wave" aria-hidden="true">∿∿∿∿∿______</div><h2>${ea[t.id][0]}</h2><p>${ea[t.id][1]}</p><span class="text-link">Open interactive example ↗</span></a>`).join('')}</div></section>`);
for(const t of atlas)add(`atlas/${t.id}`,ea[t.id][0],ea[t.id][1],crumbs('atlas/','Atlas')+head('INTERACTIVE ATLAS',ea[t.id][0],ea[t.id][1],`<div class="tag-row">${badge('Teaching simulation · not patient data')}${badge('Parameters chosen for illustration')}</div>`)+`<section class="container section compact"><div class="atlas-tool" data-atlas data-pattern="${t.spatialTerminationPattern}" data-morphology="${t.terminalActivityPattern}"><div class="atlas-controls"><fieldset><legend>Visible channels</legend>${[1,2,3,4].map(i=>`<label><input type="checkbox" value="${i}" checked/> CH${i}</label>`).join('')}</fieldset><div class="zoom-controls"><button data-zoom="in" aria-label="Zoom in on time axis">＋ Zoom in</button><button data-zoom="out" aria-label="Zoom out on time axis">− Zoom out</button><button data-reset>Reset ↺</button></div></div><div class="wave-scroll"><svg viewBox="0 0 1000 470" role="img" aria-label="Four simulated channels with a common time axis and offset markers"><text x="40" y="80">Preparing teaching waveforms; descriptions remain available below.</text></svg></div><p class="atlas-status" aria-live="polite"></p><noscript><p>Interactive waveforms require JavaScript. ${ea[t.id][1]}</p></noscript></div><div class="prose">${section('Reading this example','The horizontal axis is simulated time in seconds. Zero marks the first simulated channel offset. Amplitude is in arbitrary units (a.u.), with vertically offset channels. Dashed lines mark each channel offset on the common time axis. A separately displayed slow component is artificially generated; it is not a DC recording or an established biological mechanism. Zoom centers on the offset period.')}${section('Two independent dimensions',`Spatial pattern: ${t.spatialTerminationPattern}. Terminal activity: ${t.terminalActivityPattern==='burst'?'alternating bursts and silence':'continuous activity'}. Clinical classification requires prespecified timing thresholds and recording coverage.`)}${refs(t.relatedPaperIds)}</div></section>`);
add('methods','Research methods','Annotation, signal acquisition and statistical validation.',head('METHODS & REPRODUCIBILITY','Research methods','From operational definitions to signal chains and inference. These are methodological notes, not a validated laboratory SOP.',categoryNav())+`<section class="container section compact"><div class="three-grid">${methods.map((m,i)=>a(`methods/${m.id}/`,`<p class="eyebrow">METHOD 0${i+1}</p><h2>${em[m.id][0]}</h2><p>${em[m.id][1]}</p><span>Read method ↗</span>`,'method-card')).join('')}</div></section>`);
for(const m of methods)add(`methods/${m.id}`,em[m.id][0],em[m.id][1],crumbs('methods/','Methods')+head('METHODS',em[m.id][0],em[m.id][1])+prose(em[m.id][2].map(([h,p])=>section(h,p)).join('')+'<h2>Related literature</h2>'+refs(m.paperIds)));
add('about','Understanding termination','Electrographic cessation, clinical cessation and recovery.',head('UNDERSTANDING SEIZURE TERMINATION','After cessation, questions remain.','Define observational levels, from local electrical activity to clinical behavior.')+prose(section('Where does termination occur?','The last sustained ictal activity in a local channel, cessation across sampled regions and clinical motor cessation can occur at different times. Explicit definitions and recording coverage are essential.')+refs(['26552555','35104646'])+section('Does stopping mean recovery?','Suppression and network reorganization can follow electrographic cessation. Consciousness and behavioral recovery require independent observations; a flat waveform is not a recovery measure.')+refs(['28073789'])+'<h2>Research milestones</h2><div class="timeline">'+[['2008','Acid-sensitive channels','18536711'],['2011','Very low frequency human activity','21280091'],['2012','Critical transitions across scales','23213262'],['2013','Closed-loop cell-specific intervention','23340416'],['2018','Neural field propagation and termination','29540685'],['2022','Spatial and terminal-pattern classification','35104646'],['2025','Cross-system infraslow propagation observations','40348201']].map(([y,t,id])=>`<div><span>${y}</span><h3>${t}</h3>${refs([id])}</div>`).join('')+'</div><h2>Glossary</h2>'+facts([['SEEG / iEEG','Stereo-EEG / intracranial EEG, recording activity within electrode coverage.'],['ISA / DC-like shift','Infraslow activity / DC-like shift: descriptive slow-potential features whose interpretation depends on acquisition.'],['Critical transition','A qualitative state change in a dynamical system; model and biological mechanism must be distinguished.'],['Postictal suppression','An electrophysiological observation, not a synonym for recovered consciousness.']])));
add('framework/3r','3R framework','A project-specific operational framework.',head('PROJECT FRAMEWORK','3R: observe termination and recovery separately.','A project-specific operational framework, not an internationally established staging system.')+`<section class="container section compact"><div class="three-grid">${[['Restart','Electrographic cessation and local transition','Observe the last sustained ictal activity, local slow changes and their relative timing.'],['Rebuilding','Slow-potential recovery and network reintegration','Study the return of slow activity and connectivity reorganization without assuming one fixed trajectory.'],['Restoration','Consciousness, behavior and function','Use independent clinical observations and align functional recovery with electrophysiology.']].map(([h,t,p])=>`<article class="framework-card"><p class="eyebrow">${h}</p><h2>${t}</h2><p>${p}</p></article>`).join('')}</div><div class="callout">Stage boundaries, measurable indicators and temporal relationships require validation. Not every seizure necessarily follows three fixed, mutually exclusive stages.</div>${refs(['28073789','40348201'])}</section>`);
const bio=["Liankun Ren is a chief physician, professor and doctoral supervisor in the Department of Neurology at Xuanwu Hospital, Capital Medical University; deputy director of its Epilepsy Diagnosis and Treatment Center; and director of the Epilepsy Center and Sleep Medicine at the Jinan Regional Center of Xuanwu Hospital, National Center for Neurological Disorders. He is a recipient of a leading-talent designation under Beijing's Gaochuang program.","His professional roles include deputy head of the Epilepsy and EEG Group of the Neurological Physician Division of the Chinese Medical Doctor Association; standing committee member of the EEG and Clinical Neurophysiology Branch of the China Association Against Epilepsy; chair of the EEG and Clinical Neurophysiology Branch of the Beijing Medical Association; chair of the Brain Electrophysiology and Brain Rhythm Disorders Committee and deputy chair of the Brain Functional Disorders and Cognitive Development Committee of the Beijing Society for Neuroscience; and member of the Epilepsy and EEG Group of the Chinese Society of Neurology. He was a major contributor to a 2025 second-class National Science and Technology Progress Award, received a 2023 first-class Hebei Medical Science and Technology Award, and was recognized as an outstanding expert on the twentieth anniversary of the China Association Against Epilepsy.","His work focuses on drug-resistant epilepsy and its electrophysiological mechanisms, including mechanisms and targets for neuromodulation. Publications have appeared in Brain, Brain Stimulation, MedComm, Annals of Neurology, Neurology, Cardiovascular Research and Epilepsia. He has edited and translated academic books, led national research projects, and contributed to Chinese epilepsy and EEG guidelines and consensus statements."];
add('team','Principal investigator','Liankun Ren: public profile from the same research group.',`<section class="container pi-layout"><figure><img src="${import.meta.env.BASE_URL.replace(/\/$/,'')}/${team.image}" alt="Professor Liankun Ren" width="600" height="800"/><figcaption>Public research-group portrait · reused with authorization</figcaption></figure><div><p class="eyebrow">PRINCIPAL INVESTIGATOR</p><h1>Liankun Ren</h1><p class="pi-english">MD, PhD</p><div class="prose">${bio.map(p=>`<p>${p}</p>`).join('')}</div><p class="small">Translated from the group's public profile; role names are descriptive English translations. ${ext(team.source,'Original profile')} · Verified ${team.verifiedAt}</p></div></section><section class="container section"><h2>Public bibliography</h2><p>The original group directory spans several research areas; these entries are not all seizure-termination studies. Refer to formal publication records for bibliographic details.</p><ol class="publication-list">${team.publications.map(p=>`<li>${e(p)}</li>`).join('')}</ol></section>`);
add('work','Our work','Human SEEG and clinical neurophysiology as a starting point.',head('OUR WORK','From human observations to testable questions.','Connecting published foundations and termination-related directions in drug-resistant epilepsy, SEEG and neuromodulation.')+`<section class="container section compact"><div class="work-feature"><p class="eyebrow">PUBLISHED FOUNDATION / 2011</p><h2>Very low frequency oscillations in human epilepsy</h2><p>Ren and colleagues' Annals of Neurology study provides early human observations. Its focus is preictal VLFO; it does not directly establish a termination mechanism.</p>${refs(['21280091'])}</div><article class="prose narrow">${section('Research pathway','Human SEEG observations → reliable termination phenotypes → infraslow activity and network coupling → candidate termination-state validation → focused animal intervention → functional recovery assessment.')}<div class="callout">This is a research pathway, not a claim that every stage has been completed. Unpublished cohort results and project progress are not presented.</div>${section('3R framework','Observe electrographic cessation, network reintegration and functional recovery separately.')}${a('framework/3r/','Explore 3R ↗')}<h2>Team and other research</h2>${a('team/','Principal investigator and bibliography ↗')}</article></section>`);
add('news','Research news','Selected published findings and their evidence boundaries.',head('RESEARCH NOTES','Place new findings within their evidence.','Entries use publication years, distinguished from website verification dates.')+`<section class="container section compact"><div class="news-list">${news.map(n=>a(`news/${n.id}/`,`<span>${n.year}</span><div><h2>${en[n.id][0]}</h2><p>${en[n.id][1]}</p></div><span>↗</span>`,'')).join('')}</div></section>`);
for(const n of news)add(`news/${n.id}`,en[n.id][0],en[n.id][1],head(`RESEARCH NOTE / ${n.year}`,en[n.id][0],en[n.id][1])+prose('<p>Verified 2026-09-08. Follow the link for research notes and original sources.</p>'+refs([n.paperId])+`<div class="callout">${ep[n.paperId][3]}</div>`));
add('resources','Resources','Official literature, registry and research resources.',head('RESEARCH RESOURCES','Return to the original sources.','External links do not imply institutional collaboration.',categoryNav())+`<section class="container section compact"><div class="resource-grid">${[['PubMed','Formal publication records and abstracts','https://pubmed.ncbi.nlm.nih.gov/'],['PubMed Central','Accessible full-text literature','https://pmc.ncbi.nlm.nih.gov/'],['ClinicalTrials.gov','Registration, status and results','https://clinicaltrials.gov/'],['Chinese Clinical Trial Registry','Chinese clinical research registration','https://www.chictr.org.cn/'],['WHO ICTRP','International trial-registration search','https://trialsearch.who.int/'],['Group CDKL5 website','The same research group’s disease-research platform','https://cdkl5-care.github.io/']].map(([t,d,url])=>`<article class="method-card"><h2>${t}</h2><p>${d}</p>${ext(url,'Official website')}</article>`).join('')}</div></section>`);
add('public','Public questions','Understanding cessation, recovery and research evidence.',head('FOR EVERY READER','Questions about stopping.','Understand research concepts while retaining their evidence boundaries.')+prose(section('Why study termination?','Understanding how seizures end helps formulate mechanistic and intervention questions. Different termination patterns may reflect different processes.')+section('Does a stopped waveform mean recovery?','Not necessarily. Electrical activity, consciousness and behavior use different measures and may recover at different times.')+section('Can animal interventions be used directly in patients?','Animal research provides evidence under specific conditions. Human safety and efficacy require dedicated clinical studies.')+section('Does registration mean a treatment works?','Registration documents a study plan and status. Published results, efficacy evidence and regulatory approval are separate matters.')+refs(['18503563','28073789'])+'<p class="small">For individual care, consult a qualified clinical team.</p>'));
add('contact','Contact and collaboration','Research-group information and collaboration directions.',head('CONTACT & COLLABORATION','Connect different research methods.','Potential topics include termination phenotypes, SEEG methods, animal causal tests and recovery outcomes.')+prose(section('Research-group information','Use the investigator profile and formal institutional channels for research contact. The original CDKL5 contact form is intended for patient-family registration; do not submit research data there.')+a('team/','Principal investigator ↗','button')+ext(team.source,'Original group profile')+section('Collaboration topics','Cross-center annotation consistency; infraslow acquisition, reference and filtering robustness; interventions in termination windows; and recovery outcomes across levels.')+'<p>This website does not accept patient records or raw SEEG uploads.</p>'));
add('about/evidence-policy','Evidence policy','Inclusion, verification, citation and update rules.',head('EVIDENCE POLICY','Retain the source and the limits of every claim.','A curated navigation resource, not an exhaustive review.')+prose(section('Systems and relevance','Human, animal, ex vivo, computational and review evidence are labeled separately. Direct, supporting and background relevance are not a single quality ranking.')+section('Verification depth','Metadata come from PubMed and official registries. Available main text supports notes and figure navigation; abstract-only records are labeled. Missing information is not filled with zero or inference. Publisher figures are not reproduced.')+section('Registry status','Each record shows its registry-update and verification dates. Study termination, posted results and efficacy judgments are separate; composite outcomes retain their components and time windows.')+section('Atlas and group content','All current atlas entries are simulations without patient data. The investigator profile is reused from the same group with authorization. The research pathway and 3R are operational frameworks, not completed results.')+section('Maintenance and corrections','Content is updated after manual review. Medical conclusions are not generated on page load. If an entry differs from the original record, consult the source and report the discrepancy through formal group channels.')+`<p>Verified 2026-09-08: ${papers.length} papers and ${trials.length} registered studies. Registry coverage is currently centered on ClinicalTrials.gov.</p>`));
