import paperData from '../data/papers.json';
import trialData from '../data/trials.json';
import topics from '../data/topics.json';
import methods from '../data/methods.json';
import atlas from '../data/atlas.json';
import news from '../data/news.json';
import team from '../data/team.json';

type Figure={label:string;title:string;observation:string;interpretation:string};
type Paper=typeof paperData[number] & {figures?:Figure[];readingNote?:string};
const papers:Paper[]=paperData;
const trials=trialData;
export const u=(p='')=>`${import.meta.env.BASE_URL.replace(/\/$/,'')}/${p.replace(/^\//,'')}`;
const e=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const ext=(url:string,label:string)=>`<a class="source-link" href="${e(url)}" target="_blank" rel="noreferrer">${e(label)} <span aria-hidden="true">↗</span></a>`;
const link=(p:string,label:string,cls='text-link')=>`<a class="${cls}" href="${u(p)}">${label}</a>`;
const systems:Record<string,string>={human:'人类研究',animal:'动物研究',exvivo:'离体研究',model:'计算模型',review:'综述／共识'};
const rel:Record<string,string>={direct:'直接相关',supporting:'支持性证据',context:'背景研究'};
const badge=(text:string,cls='')=>`<span class="badge ${cls}">${e(text)}</span>`;
const refs=(ids:string[])=>`<div class="reference-list">${ids.map(id=>{const p=papers.find(p=>p.id===id);return p?link(`library/${id}/`,`${e(p.titleZh)} <span>${p.year} · PMID ${id} ↗</span>`,'reference-row'):''}).join('')}</div>`;
const crumbs=(parent='首页',path='')=>`<div class="breadcrumbs">${link('', '首页','')}${path?`<span>/</span>${link(path,parent,'')}`:''}<span>/</span><span>当前页面</span></div>`;
const head=(eyebrow:string,title:string,desc:string,extra='')=>`<section class="container inner-hero"><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="lead">${desc}</p>${extra}</section>`;
const topicCard=(t:typeof topics[number])=>`<a class="topic-card tone-${t.index}" href="${u(`research/${t.id}/`)}"><span class="card-top"><span>${t.index} / RESEARCH</span><span>↗</span></span><span class="topic-symbol" aria-hidden="true">${['∿','≈','⋈','⌘','↗','◌'][Number(t.index)-1]}</span><h3>${t.title}</h3><p>${t.subtitle}</p></a>`;
const filterNav=()=>`<nav class="subnav" aria-label="文献与研究导航">${link('evidence/','分类总览','')}${link('library/','文献库','')}${link('trials/','注册研究','')}${link('methods/','研究方法','')}${link('resources/','资源导航','')}</nav>`;
function paperCard(p:Paper){return `<article class="paper-card result-card" data-search="${e([p.titleZh,p.titleOriginal,p.authors.join(' '),p.pmid,p.doi].join(' ').toLowerCase())}" data-system="${p.studySystems.join(' ')}" data-topic="${p.topicIds.join(' ')}" data-year="${p.year}" data-type="${e(p.design)}" data-relevance="${p.relevanceTier}"><div class="paper-meta"><span>${p.year} / ${e(p.journal)}</span><span>${p.studySystems.map(s=>badge(systems[s])).join('')}</span></div><h3>${link(`library/${p.id}/`,e(p.titleZh),'')}</h3><p class="original-title" lang="en">${e(p.titleOriginal)}</p><p>${e(p.findings[0])}</p><div class="paper-foot"><span>${badge(rel[p.relevanceTier],'outline')} ${p.figures?badge('全文要点','accent'):badge('摘要概述','outline')}</span>${link(`library/${p.id}/`,'阅读解读 ↗','')}</div></article>`;}
function trialCard(t:typeof trials[number]){return `<article class="trial-card result-card" data-search="${e((t.id+' '+t.titleZh+' '+t.briefTitle).toLowerCase())}" data-status="${t.statusRaw}" data-endpoint="${e(t.endpointCategory)}" data-relevance="${t.relevanceTier}" data-country="${e(t.countries.join('|'))}" data-type="${t.studyType}" data-year="${t.registryLastUpdatedAt}"><div class="paper-meta"><span>${t.id}</span>${badge(t.statusZh,t.statusRaw==='RECRUITING'?'accent':'')}</div><h3>${link(`trials/${t.slug}/`,e(t.titleZh),'')}</h3><p>${e(t.inclusionReason)}</p><p class="small">${e(t.endpointCategory)} · ${rel[t.relevanceTier]}</p><div class="paper-foot"><span>核验 ${t.verifiedAt}</span>${link(`trials/${t.slug}/`,'查看登记 ↗','')}</div></article>`;}
const select=(name:string,label:string,options:{value:string,label:string}[])=>`<label>${label}<select name="${name}"><option value="">全部${label}</option>${options.map(x=>`<option value="${e(x.value)}">${e(x.label)}</option>`).join('')}</select></label>`;
const unique=(values:string[])=>[...new Set(values)].map(v=>({value:v,label:v}));
const filterForm=(kind:string,options:string)=>`<form class="filters" data-filter-form data-kind="${kind}" role="search"><label class="search-field">${kind==='papers'?'检索文献':'检索注册研究'}<input name="q" type="search" placeholder="${kind==='papers'?'题名、作者、PMID 或 DOI':'研究名称、关键词或注册号'}" autocomplete="off" /></label><div class="filter-selects">${options}<label>排序<select name="sort"><option value="new">时间由新到旧</option><option value="old">时间由旧到新</option></select></label><button type="reset" class="reset">清除筛选 ↺</button></div><p class="result-count" aria-live="polite"></p></form>`;
function paperPage(p:Paper){return `<div class="container">${crumbs('文献库','library/')}</div>${head(`LITERATURE / ${p.year}`,e(p.titleZh),e(p.titleOriginal),`<div class="tag-row">${p.studySystems.map(s=>badge(systems[s])).join('')}${badge(rel[p.relevanceTier],'outline')}${badge(p.figures?'全文要点':'基于摘要','outline')}</div>`)}<div class="container reading-layout"><article class="prose"><section><h2>01 / 文献基础信息</h2><p>${e(p.authors.join(', '))}</p><p><strong>${e(p.journal)}</strong> · ${p.year} · ${e(p.volume)} · ${e(p.pages)}</p><p>${ext(p.url,`PubMed · ${p.id}`)} ${p.doi?ext(`https://doi.org/${p.doi}`,`DOI · ${p.doi}`):''} ${p.pmcid?ext(`https://pmc.ncbi.nlm.nih.gov/articles/${p.pmcid}/`,'PMC 原文'):''}</p><p class="small">正式发表 · ${e(p.design)} · 本站核验 ${p.verifiedAt}</p></section><section><h2>02 / 研究逻辑</h2><p class="question">${e(p.question)}</p><p>${e(p.findings[0])}</p></section><section><h2>03 / 机制与方法</h2><p>${e(p.design)} → ${e(p.inclusionReason)} → 对终止相关证据作条件化解释。</p><div class="callout">${e(p.limitations[0])}</div></section>${p.figures?`<section><h2>04 / 主图表导航</h2><p class="small">${e(p.readingNote)} 每条链接前往原文，解释限于该研究。</p><div class="figure-list">${p.figures.map(f=>`<details><summary><span>${e(f.label)}</span> ${e(f.title)}</summary><p><strong>设计与观察：</strong>${e(f.observation)}</p><p><strong>解释边界：</strong>${e(f.interpretation)}</p>${ext(`https://pmc.ncbi.nlm.nih.gov/articles/${p.pmcid}/`,'打开原文图表')}</details>`).join('')}</div></section>`:`<section><h2>04 / 原文获取范围</h2><p>本条为摘要概述。未获取并核验完整正文与补充材料，因此不提供逐图数据解读。</p></section>`}<section><h2>05 / 证据归纳</h2><p>${badge(p.evidenceLabels.join(' · '))}</p><p>${e(p.findings[0])}</p><p>对应主题：${p.topicIds.map(id=>link(`research/${id}/`,e(topics.find(t=>t.id===id)?.title||id))).join(' · ')}</p></section><section><h2>06 / 客观评价</h2><p><strong>研究价值：</strong>${e(p.question)} 这为相关专题提供了可以进一步检验的切入点。</p><p><strong>局限：</strong>${e(p.limitations[0])}</p></section>${p.relatedTrialIds.length?`<section><h2>关联注册研究</h2>${p.relatedTrialIds.map(id=>{const t=trials.find(t=>t.id===id)!;return trialCard(t)}).join('')}</section>`:''}</article><aside class="reading-aside"><p class="eyebrow">READING NOTES</p><h3>把证据放回研究条件。</h3><p>${e(p.modelOrPopulation)}</p><p>资料范围：${p.fullTextAccess==='full-text'?'已获取主文':'已核验摘要'}</p><p>核验定位：${e(p.sourceLocators.join('；'))}</p>${link('about/evidence-policy/','证据与引用规则 ↗')}<hr/><h3>相关研究</h3>${refs(papers.filter(x=>x.id!==p.id&&x.topicIds.some(id=>p.topicIds.includes(id))).slice(0,3).map(x=>x.id))}</aside></div>`;}
function dateFmt(d:{date:string,type?:string}|null){return d?`${e(d.date)} · ${d.type==='ACTUAL'?'实际':d.type==='ESTIMATED'?'预计':'类型未报告'}`:'未报告';}
const designLabels:Record<string,string>={RANDOMIZED:'随机分配',NON_RANDOMIZED:'非随机',PARALLEL:'平行分组',SINGLE_GROUP:'单组',TREATMENT:'治疗研究',DOUBLE:'双盲',TRIPLE:'三方盲法',QUADRUPLE:'四方盲法',NONE:'开放标签',NA:'不适用'};
function designText(d:Record<string,unknown>){return ['allocation','interventionModel'].map(k=>designLabels[String(d[k])]||String(d[k]||'')).filter(Boolean).join(' · ');}
function trialPage(t:typeof trials[number]){return `<div class="container">${crumbs('注册研究','trials/')}</div>${head(`REGISTERED STUDY / ${t.id}`,e(t.titleZh),e(t.briefTitle),`<div class="tag-row">${badge(t.statusZh)}${badge(t.endpointCategory)}${badge(rel[t.relevanceTier],'outline')}</div>`)}<div class="container reading-layout"><article class="prose"><div class="callout"><strong>与发作终止的关系</strong><p>${e(t.inclusionReason)}</p><p>${e(t.summary)}</p></div><section><h2>研究设计</h2><dl class="facts"><dt>正式名称</dt><dd lang="en">${e(t.officialTitle)}</dd><dt>申办方</dt><dd>${e(t.sponsor)}</dd><dt>研究类型／期别</dt><dd>${t.studyType==='INTERVENTIONAL'?'干预性研究':e(t.studyType)} · ${t.phase.map(x=>x==='NA'?'期别不适用':x==='PHASE3'?'III 期':e(x)).join(' / ')||'期别未报告'}</dd><dt>设计</dt><dd>${e(designText(t.design))}</dd><dt>年龄</dt><dd>${e(t.populationSummary)}</dd><dt>入组</dt><dd>${t.enrollment.count??'未报告'} · ${t.enrollment.type==='ACTUAL'?'实际入组':'预计入组'}（以注册记录口径为准）</dd><dt>地区</dt><dd>${e(t.countries.join('、')||'未报告')}</dd></dl></section><section><h2>干预与对照</h2>${t.interventions.map(x=>`<div class="compact-block"><strong>${e(x.name)}</strong><span class="small"> ${e(x.type)}</span></div>`).join('')}<p class="small">本页展示研究方案信息，不提供个体用药或刺激参数建议。</p></section><section><h2>主要终点与时间窗</h2><p>以下保留注册原始字段，避免把复合终点简化为单纯终止率。</p>${t.primaryOutcomes.map((x,i)=>`<div class="outcome"><span class="eyebrow">OUTCOME ${String(i+1).padStart(2,'0')}</span><h3 lang="en">${e(x.measure)}</h3>${'description' in x?`<p lang="en">${e(x.description)}</p>`:''}<p><strong>时间窗：</strong><span lang="en">${e(x.timeFrame)}</span></p></div>`).join('')}</section><section><h2>状态与结果</h2><dl class="facts"><dt>官方状态</dt><dd>${e(t.statusZh)} / ${e(t.statusRaw)}</dd><dt>终止原因</dt><dd>${e(t.whyStopped||'当前登记字段未报告／不适用')} ${t.id==='NCT04839601'?'（入组不足）':''}</dd><dt>注册结果</dt><dd>${t.resultsPosted?'平台已发布结果':'平台未发布结果'}</dd><dt>开始日期</dt><dd>${dateFmt(t.startDate)}</dd><dt>主要完成</dt><dd>${dateFmt(t.primaryCompletionDate)}</dd><dt>研究完成</dt><dd>${dateFmt(t.completionDate)}</dd></dl>${t.statusRaw==='TERMINATED'?`<div class="callout">“研究提前终止”是试验执行状态，不代表“发作成功终止”，也不能据此自行判断无效或不安全。</div>`:''}</section>${t.relatedPaperIds.length?`<section><h2>已核验的关联论文</h2>${refs(t.relatedPaperIds)}</section>`:'<p class="small">本站尚未核验与本注册号对应的正式结果论文。注册页面中的参考文献不自动等于本试验的结果。</p>'}</article><aside class="reading-aside"><p class="eyebrow">REGISTRY SNAPSHOT</p><h3>${t.id}</h3><p>平台更新：${t.registryLastUpdatedAt}</p><p>本站核验：${t.verifiedAt}</p><p>数据来自官方 API 快照。招募状态以最新官方记录和研究中心为准。</p>${ext(t.canonicalUrl,'查看官方记录')}<hr/>${link('trials/','返回注册研究库 ←')}</aside></div>`;}

type Page={path:string,title:string,description:string,html:string};
export const nav=[{path:'about/',label:'认识终止'},{path:'research/',label:'相关研究'},{path:'atlas/',label:'终止图谱'},{path:'evidence/',label:'文献与注册'},{path:'work/',label:'我们的工作'},{path:'news/',label:'研究动态'},{path:'team/',label:'主要研究者'}];
export const pages:Page[]=[];
const add=(path:string,title:string,description:string,html:string)=>pages.push({path:path.replace(/\/$/,''),title,description,html});

const portalCard=(path:string,title:string,description:string,tone:string,extra='')=>`<a class="portal-card ${tone} ${extra}" href="${u(path)}"><span class="portal-arrow" aria-hidden="true">↗</span><div><h2>${title}</h2><p>${description}</p></div></a>`;
add('','首页','癫痫发作终止与脑功能恢复：研究方向、文献与注册研究、终止图谱和课题组工作。',`
<section class="portal-heading"><h1>癫痫发作终止</h1><p>从人类电生理出发，连接基础机制与临床研究。</p></section>
<nav class="portal-grid" aria-label="网站主要板块">
${portalCard('about/','认识<span class=portal-nobreak>发作终止</span>','基本概念、研究历程与终止后的恢复。','portal-cream')}
${portalCard('news/','研究动态','近期研究进展与原始文献来源。','portal-sand')}
${portalCard('work/','我们的工作','人类 SEEG、研究积累与课题组研究路线。','portal-peach','portal-wide')}
${portalCard('research/','相关研究','终止表型、超慢活动、网络与机制。','portal-sage')}
${portalCard('evidence/','文献与注册','动物与临床文献、注册研究及方法资源。','portal-stone')}
${portalCard('atlas/','终止图谱','通过教学模拟，观察不同终止模式。','portal-apricot','portal-wide')}
</nav>`);

add('evidence','文献与注册','文献、注册研究、方法与资源的分类入口。',head('LITERATURE & REGISTERED STUDIES','文献与注册','选择资料类型，进入列表后检索或查看详细内容。')+`<nav class="portal-grid portal-subgrid" aria-label="文献与注册分类">
${portalCard('library/','研究文献',`${papers.length} 篇精选文献 · 人类、动物、离体与计算模型。`,'portal-cream')}
${portalCard('trials/','注册研究',`${trials.length} 项已核验登记 · 方案、状态、终点与结果。`,'portal-peach')}
${portalCard('methods/','研究方法','终止标注、慢电位处理与统计验证。','portal-sage')}
${portalCard('resources/','资源导航','文献数据库、官方注册平台与相关资源。','portal-stone')}
</nav>`);

add('research','研究方向','六个专题连接发作终止、超慢活动、网络动力学和功能恢复。',head('RESEARCH LANDSCAPE','相关研究','选择一个研究方向，查看研究问题、证据与相关文献。')+`<section class="container section compact"><div class="topic-grid">${topics.map(topicCard).join('')}</div></section>`);
for(const t of topics)add(`research/${t.id}`,t.title,t.question,`<div class="container">${crumbs('相关研究','research/')}</div>`+head(`${t.index} / RESEARCH`,t.title,t.subtitle)+`<div class="container reading-layout"><article class="prose"><h2>${t.question}</h2><p>${t.summary}</p><h2>已知证据与待解问题</h2><div class="callout">${t.boundary}</div><h2>阅读起点</h2>${refs(t.paperIds)}<h2>如何继续研究</h2><p>从清晰的观测定义出发，区分记录到的现象、模型解释与干预检验。每项新结果都需要说明适用体系、分析时间窗和独立验证范围。</p>${t.id==='recovery'?link('framework/3r/','了解 3R 操作性框架 ↗'):link('methods/','研究方法与验证 ↗')}</article><aside class="reading-aside"><p class="eyebrow">EXPLORE FURTHER</p>${topics.filter(x=>x.id!==t.id).map(x=>link(`research/${x.id}/`,x.title,'aside-link')).join('')}</aside></div>`);

add('library','文献库','可检索的人类、动物、离体、计算及综述研究。',head('EVIDENCE LIBRARY','文献与研究证据','按研究体系、科学问题和相关程度检索。精选导航不构成系统综述。',filterNav())+`<section class="container section compact">${filterForm('papers',select('system','研究体系',Object.entries(systems).map(([value,label])=>({value,label})))+select('topic','主题',topics.map(t=>({value:t.id,label:t.title})))+select('year','年份',unique(papers.map(p=>p.year)).sort((a,b)=>b.value.localeCompare(a.value)))+select('type','研究类型',unique(papers.map(p=>p.design)))+select('relevance','相关程度',Object.entries(rel).map(([value,label])=>({value,label}))))}<div class="result-list">${[...papers].sort((a,b)=>b.year.localeCompare(a.year)).map(paperCard).join('')}</div><p class="empty-state" hidden>没有符合条件的文献。请减少筛选条件或尝试其他关键词。</p></section>`);
papers.forEach(p=>add(`library/${p.id}`,p.titleZh,p.findings[0],paperPage(p)));
add('trials','注册研究','区分研究状态、主要终点、时间窗与结果发布情况。',head('CLINICAL STUDY REGISTRY','从注册记录，读懂临床问题。','直接相关研究与长期控制背景研究分组标注；注册状态不等于疗效。',filterNav())+`<section class="container section compact">${filterForm('trials',select('status','研究状态',unique(trials.map(t=>t.statusRaw)).map(x=>({value:x.value,label:trials.find(t=>t.statusRaw===x.value)!.statusZh})))+select('endpoint','终点类别',unique(trials.map(t=>t.endpointCategory)))+select('relevance','相关程度',Object.entries(rel).map(([value,label])=>({value,label})))+select('country','地区',unique(trials.flatMap(t=>t.countries)))+select('type','研究类型',unique(trials.map(t=>t.studyType))))}<div class="result-list">${trials.map(trialCard).join('')}</div><p class="empty-state" hidden>没有符合条件的注册研究。</p><div class="callout small">首版收录 ClinicalTrials.gov 的已核验记录；中国注册中心和 WHO 检索覆盖仍有限。本页不是全部相关试验清单。每条记录保留平台更新与本站核验日期。</div></section>`);
trials.forEach(t=>add(`trials/${t.slug}`,t.titleZh,t.inclusionReason,trialPage(t)));

add('atlas','终止图谱','教学模拟展示终止的空间和波形维度。',head('SEIZURE OFFSET ATLAS','沿着波形，观察一次停止。','独立比较空间终止顺序与末段活动形态。所有当前示例均为原创教学模拟。')+`<section class="container section compact"><div class="atlas-grid">${atlas.map((a,i)=>`<a class="atlas-card" href="${u(`atlas/${a.id}/`)}"><span class="eyebrow">EXAMPLE 0${i+1} / ${badge('教学模拟')}</span><div class="mini-wave" aria-hidden="true">${i===2?'∿__∿__∿____':'∿∿∿∿∿______'}</div><h2>${a.title}</h2><p>${a.description}</p><span class="text-link">打开交互示例 ↗</span></a>`).join('')}</div></section>`);
for(const a of atlas)add(`atlas/${a.id}`,a.title,a.description,head('INTERACTIVE ATLAS',a.title,a.description,`<div class="tag-row">${badge('教学模拟 · 非患者记录','accent')}${badge('参数为教学设定','outline')}</div>`)+`<section class="container section compact"><div class="atlas-tool" data-atlas="${a.id}" data-pattern="${a.spatialTerminationPattern}" data-morphology="${a.terminalActivityPattern}"><div class="atlas-controls"><fieldset><legend>显示通道</legend>${[1,2,3,4].map(i=>`<label><input type="checkbox" name="channel" value="${i}" checked /> CH${i}</label>`).join('')}</fieldset><div class="zoom-controls"><button data-zoom="in" aria-label="放大时间轴">＋ 放大</button><button data-zoom="out" aria-label="缩小时间轴">− 缩小</button><button data-reset>复位 ↺</button></div></div><div class="wave-scroll"><svg id="atlas-svg" viewBox="0 0 1000 470" role="img" aria-label="四通道教学模拟波形，共同时间轴和终止标记"><text x="40" y="80">正在准备教学波形；图谱说明可在下方阅读。</text></svg></div><p class="atlas-status" aria-live="polite"></p><noscript><p>交互波形需要 JavaScript。本例描述：${a.description}</p></noscript></div><div class="prose"><h2>如何阅读这个示例</h2><p>横轴为模拟时间（秒），0 秒表示首个模拟通道的终止。纵向振幅单位为任意单位（a.u.），各通道错位显示。虚线标记各通道的终止；共同时间轴便于比较先后。</p><p>模拟信号包含人为设定的慢成分，单独列于下方。它用于演示并列观察方式，不代表 DC 记录或已经证实的生物机制。缩放以终止附近为中心。</p><h2>两个独立的分类维度</h2><p>本例空间模式：${a.spatialTerminationPattern==='synchronous'?'同步':'异步'}；末段活动：${a.terminalActivityPattern==='burst'?'爆发与静默交替':'持续放电'}。临床分类需要预先定义时间阈值和记录范围。</p>${refs(a.relatedPaperIds)}</div></section>`);

add('methods','研究方法','终止标注、采集与处理以及统计验证。',head('METHODS & REPRODUCIBILITY','让现象经得起复核。','从标注定义到信号链，再到验证与推断。以下为研究方法说明，不是未经验证的课题组 SOP。',filterNav())+`<section class="container section compact"><div class="topic-grid">${methods.map((m,i)=>`<a class="method-card" href="${u(`methods/${m.id}/`)}"><p class="eyebrow">METHOD 0${i+1}</p><h2>${m.title}</h2><p>${m.intro}</p><span>阅读方法 ↗</span></a>`).join('')}</div></section>`);
for(const m of methods)add(`methods/${m.id}`,m.title,m.intro,head('METHODS',m.title,m.intro)+`<article class="container prose narrow">${m.sections.map(([h,p])=>`<section><h2>${h}</h2><p>${p}</p></section>`).join('')}<h2>相关研究</h2>${refs(m.paperIds)}</article>`);

add('about','认识发作终止','电生理终止、临床停止与脑功能恢复的基本概念。',head('UNDERSTANDING SEIZURE TERMINATION','发作停止之后，问题仍在继续。','从局部电活动到全身表现，明确观察层级，才能理解“终止”。')+`<article class="container prose narrow"><section><h2>“终止”发生在哪里？</h2><p>局部通道的最后一次持续发作活动、记录范围内整体发作停止，以及临床运动停止，可能对应不同时间点。研究需要给出具体定义和观测范围。</p>${refs(['26552555','35104646'])}</section><section><h2>“停止”是否意味着恢复？</h2><p>电活动终止后还可能出现抑制和网络重组。意识及行为的恢复需要独立记录，不能仅凭波形变平判定。</p>${refs(['28073789'])}</section><section><h2>几个研究里程碑</h2><div class="timeline">${[['2008','从酸敏感通道到多尺度机制','18536711'],['2011','人类极低频活动的观察','21280091'],['2012','跨尺度临界转换的动力学解释','23213262'],['2013','慢性自发发作的闭环细胞干预','23340416'],['2018','传播与终止的神经场模型','29540685'],['2022','空间与末段形态的双维度分类','35104646'],['2025','超慢传播与终止的跨体系观察','40348201']].map(([year,title,id])=>`<div><span>${year}</span><h3>${title}</h3>${refs([id])}</div>`).join('')}</div></section><section><h2>术语小辞典</h2><dl class="facts"><dt>SEEG / iEEG</dt><dd>立体定向脑电／颅内脑电，直接记录被电极覆盖区域的活动。</dd><dt>ISA / DC-like shift</dt><dd>超慢活动／类 DC 位移：描述缓慢电位特征，解释需要采集链支持。</dd><dt>临界转换</dt><dd>动力系统状态发生定性变化的理论框架；需区分模型与生物机制。</dd><dt>发作后抑制</dt><dd>终止后的电生理抑制现象，不是意识恢复的同义词。</dd></dl></section></article>`);
add('framework/3r','3R 研究框架','课题组操作性框架：Restart、Rebuilding、Restoration。',head('PROJECT FRAMEWORK','3R：把终止与恢复分开观察。','课题组提出的操作性研究框架，尚非国际通用分期。')+`<section class="container section compact"><div class="three-grid">${[['01','Restart','电生理终止与局部转换','观察最后持续发作活动、局部超慢变化及它们的相对时序。'],['02','Rebuilding','慢电位恢复与网络重新整合','研究超慢活动回归及网络连接重组；不预设单一恢复轨迹。'],['03','Restoration','意识、行为与功能恢复','采用独立的临床记录观察恢复进程，并与电生理过程对齐。']].map(([n,en,title,p])=>`<article class="framework-card"><span class="eyebrow">${n} / ${en}</span><h2>${title}</h2><p>${p}</p></article>`).join('')}</div><div class="callout">阶段边界、可测指标及先后关系需要验证。此框架用于提出可检验问题，不代表每次发作都按固定顺序经历三个互斥阶段。</div>${refs(['28073789','40348201'])}</section>`);

add('team','主要研究者','任连坤教授：沿用课题组 CDKL5 网站公开研究者介绍。',`<section class="container pi-layout"><figure><img src="${u(team.image)}" alt="任连坤教授" width="600" height="800"/><figcaption>课题组公开照片 · 沿用参考站</figcaption></figure><div><p class="eyebrow">PRINCIPAL INVESTIGATOR</p><h1>${team.name}</h1><p class="pi-english">${team.nameEn}</p><div class="prose">${team.bio.map(p=>`<p>${e(p)}</p>`).join('')}</div><p class="small">资料来源：${ext(team.source,'课题组主要研究者页面')} · 核对日期 ${team.verifiedAt}</p></div></section><section class="container section"><h2>公开论文目录</h2><p>沿用课题组页面的论文目录，涵盖多个研究方向；不将其全部归为发作终止研究。条目元数据以正式发表记录为准。</p><ol class="publication-list">${team.publications.map(p=>`<li>${e(p)}</li>`).join('')}</ol></section>`);
add('work','我们的工作','以人类 SEEG 和临床神经电生理为基础的研究路径。',head('OUR WORK','从人类观察，走向可检验的问题。','围绕耐药性癫痫、SEEG 与神经调控，连接已有研究积累和终止相关研究方向。')+`<section class="container section compact"><div class="work-feature"><p class="eyebrow">PUBLISHED FOUNDATION / 2011</p><h2>人类癫痫中的极低频振荡</h2><p>任连坤等发表于 Annals of Neurology 的工作，为超慢活动研究提供早期人类观察。其研究重点在发作前 VLFO，不直接证明终止机制。</p>${refs(['21280091'])}</div><article class="prose narrow"><h2>当前网站组织的研究路线</h2><p>人类 SEEG 观察 → 可靠终止表型 → 超慢活动与网络耦合 → 候选终止状态验证 → 聚焦的动物干预 → 功能恢复评价。</p><div class="callout">这是一条研究路线，不代表各阶段均已有完成成果。未公开队列数据及具体项目进度不在本页展示。</div><h2>3R 框架</h2><p>分别观察电生理停止、网络重新整合和功能恢复，明确不同结局之间的关系。</p>${link('framework/3r/','阅读 3R 框架 ↗')}<h2>团队与其他研究</h2>${link('team/','主要研究者及公开论文目录 ↗')}</article></section>`);
add('news','研究动态','精选论文及领域进展。',head('RESEARCH NOTES','把新发现，放回证据之中。','按实际论文发表年份展示，区别事件时间与本站核验时间。')+`<section class="container section compact"><div class="news-list">${news.map(n=>`<a href="${u(`news/${n.id}/`)}"><span>${n.year}</span><div><h2>${n.title}</h2><p>${n.summary}</p></div><span>↗</span></a>`).join('')}</div></section>`);
for(const n of news)add(`news/${n.id}`,n.title,n.summary,head(`RESEARCH NOTE / ${n.year}`,n.title,n.summary)+`<article class="container prose narrow"><p>核验日期：2026-09-08。以下链接进入研究解读与原始来源。</p>${refs([n.paperId])}<div class="callout">${e(papers.find(p=>p.id===n.paperId)!.limitations[0])}</div></article>`);
add('resources','资源导航','官方文献、注册平台与研究工具入口。',head('RESEARCH RESOURCES','从这里，回到原始来源。','外部资源导航；不表示与所列机构存在合作关系。',filterNav())+`<section class="container section compact"><div class="resource-grid">${[['PubMed','正式文献记录与摘要','https://pubmed.ncbi.nlm.nih.gov/'],['PubMed Central','公开可用的论文正文','https://pmc.ncbi.nlm.nih.gov/'],['ClinicalTrials.gov','临床研究注册、状态与结果','https://clinicaltrials.gov/'],['中国临床试验注册中心','中国临床研究注册查询','https://www.chictr.org.cn/'],['WHO ICTRP','国际临床试验注册检索入口','https://trialsearch.who.int/'],['课题组 CDKL5 网站','同一团队的疾病研究与关爱平台','https://cdkl5-care.github.io/']].map(([title,p,url])=>`<article class="method-card"><h2>${title}</h2><p>${p}</p>${ext(url,'打开官方网站')}</article>`).join('')}</div></section>`);
add('public','公众问答','帮助公众区分研究观察、发作停止与功能恢复。',head('FOR EVERY READER','几个关于“停止”的问题。','理解研究使用的概念，阅读时保留证据边界。')+`<article class="container prose narrow">${[['为什么研究发作终止？','了解发作如何结束，有助于提出新的机制与干预问题。不同终止方式可能反映不同过程。'],['波形停止后，人就恢复了吗？','不一定。电生理活动、意识和行为使用不同观测指标，可能在不同时间恢复。'],['动物中有效的干预能直接用于患者吗？','动物研究提供特定模型下的依据，人体安全性和疗效需要专门临床研究。'],['注册研究意味着治疗已经有效吗？','注册说明研究计划和状态；结果发表、疗效证据和适应证批准是不同事项。']].map(([h,p])=>`<section><h2>${h}</h2><p>${p}</p></section>`).join('')}${refs(['18503563','28073789'])}<p class="small">本页用于理解科研概念，个体诊疗请联系专业医疗团队。</p></article>`);
add('contact','联系与合作','课题组联系及研究合作入口。',head('CONTACT & COLLABORATION','让不同研究方法相遇。','欢迎围绕终止表型、SEEG 方法、动物因果验证和恢复结局开展学术交流。')+`<article class="container prose narrow"><h2>课题组信息入口</h2><p>主要研究者及团队公开资料请见下方页面。原站联系页用于其患者家庭登记；科研合作联系请通过所属机构的正式渠道，不在该登记表提交研究数据。</p>${link('team/','主要研究者 ↗','button')}${ext('https://cdkl5-care.github.io/pi','课题组原始资料')}<h2>可讨论的合作方向</h2><ul><li>跨中心终止标注与表型一致性。</li><li>超慢活动采集、参考及滤波稳健性。</li><li>终止窗口的实验干预与多层级恢复结局。</li></ul><p>本网站不接收患者病历或原始 SEEG 上传。</p></article>`);
add('about/evidence-policy','证据与更新规则','网站内容纳入、引用、核验和更新原则。',head('EVIDENCE POLICY','每条结论，都保留来源和边界。','精选内容导航，不宣称穷尽全部研究。')+`<article class="container prose narrow"><h2>研究体系与相关程度</h2><p>人类、动物、离体、模型和综述分别标注。直接相关、支持性证据及背景研究说明与终止主题的关系，不构成单一质量排名。</p><h2>核验深度</h2><p>元数据来自 PubMed 和官方注册平台。正文可获得时提供全文要点与主图表导航；仅获得摘要时明确标注。缺失信息不补写为零或推测值。网站不提供未经核验的全文翻译或原图复制。</p><h2>注册状态</h2><p>每条记录分别显示平台更新日期与本站核验日期。试验提前终止、结果发布和疗效判断分开；复合终点保留组成与时间窗。</p><h2>图谱与课题组内容</h2><p>首版图谱均为教学模拟，不含患者数据。主要研究者介绍经用户确认沿用同一课题组公开页面。研究路线与 3R 标为操作性框架，不充作已完成结果。</p><h2>维护与纠错</h2><p>内容通过手动复核后更新，不在访问时自动生成医学结论。如发现条目与原始记录有出入，请以原始来源为准并通过课题组正式渠道反馈。</p><p>本轮核验：2026-09-08；文献 ${papers.length} 条，注册研究 ${trials.length} 条。首版注册数据库为 ClinicalTrials.gov，其他平台的检索覆盖有限。</p></article>`);
