import { chromium } from 'playwright';
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';
const base=process.env.TEST_URL||'http://127.0.0.1:4321';const out='docs/qa-artifacts';fs.mkdirSync(out,{recursive:true});
const chrome=process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe';
const browser=await chromium.launch({headless:true,executablePath:chrome});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',err=>errors.push(err.message));const results=[];
async function test(name,fn){try{await fn();results.push({name,pass:true});console.log('PASS',name)}catch(err){results.push({name,pass:false,error:err.message});console.log('FAIL',name,err.message)}}
async function go(p=''){return page.goto(base+'/'+p,{waitUntil:'networkidle'})}
const visible=()=>page.locator('.result-card:visible').count();
await test('Home and topic navigation',async()=>{await go();assert.equal(await page.locator('h1').count(),1);assert.equal(await page.locator('.portal-card').count(),6);await page.locator('.portal-card[href$="research/"]').click();assert.equal(await page.locator('.topic-card').count(),6);await page.locator('.topic-card').first().click();assert(page.url().includes('/research/phenotypes/'));assert(await page.locator('h1').innerText()==='终止表型')});
await test('PMID search and persistence',async()=>{await go('library/');await page.locator('input[name=q]').fill('23340416');await page.waitForFunction(()=>document.querySelector('.result-count').textContent.includes('显示 1 /'));assert.equal(await visible(),1);assert(page.url().includes('q=23340416'));await page.reload();assert.equal(await visible(),1);assert.equal(await page.locator('input[name=q]').inputValue(),'23340416')});
await test('DOI search',async()=>{await page.locator('input[name=q]').fill('10.1038/ncomms2376');await page.waitForFunction(()=>location.search.includes('ncomms2376'));assert.equal(await visible(),1)});
await test('Chinese search',async()=>{await page.locator('input[name=q]').fill('酸化');await page.waitForFunction(()=>decodeURIComponent(location.search).includes('酸化'));assert.equal(await visible(),1)});
await test('Zero results and reset',async()=>{await page.locator('input[name=q]').fill('zz-no-result-zz');await page.locator('.empty-state').waitFor({state:'visible'});assert.equal(await visible(),0);await page.locator('button[type=reset]').click();await page.waitForFunction(()=>document.querySelector('.result-count').textContent.includes('显示 20 /'));assert.equal(await visible(),20)});
await test('Combination filters and history',async()=>{await page.locator('select[name=system]').selectOption('animal');const n=await visible();assert(n>0&&n<20);await page.locator('select[name=topic]').selectOption('intervention');assert(await visible()<=n);await page.goBack();assert.equal(await page.locator('select[name=topic]').inputValue(),'');assert.equal(await page.locator('select[name=system]').inputValue(),'animal')});
await test('Paper / trial bidirectional links',async()=>{await go('library/31140596/');await page.locator('.trial-card a').first().click();assert(page.url().includes('nct01390220'));await page.locator('a[href$="library/31140596/"]').click();assert(page.url().includes('library/31140596'));await page.reload();assert.equal(await page.locator('h1').count(),1)});
await test('Trial status and outcome filter',async()=>{await go('trials/');await page.locator('select[name=status]').selectOption('RECRUITING');assert.equal(await visible(),1);await page.locator('select[name=endpoint]').selectOption('持续状态控制');assert.equal(await visible(),1);await page.reload();assert.equal(await visible(),1);await page.locator('.trial-card:visible h3 a').click();const text=await page.locator('main').innerText();assert(text.includes('预计入组'));assert(text.includes('2026-08-04'));assert(text.includes('平均 1 年'))});
await test('Terminated does not mean seizure stopped',async()=>{await go('trials/nct04839601/');const text=await page.locator('main').innerText();assert(text.includes('研究提前终止'));assert(text.includes('入组不足'));assert(text.includes('长期发作控制'));assert(text.includes('不代表'))});
await test('Atlas zoom channels and reset',async()=>{await go('atlas/asynchronous/');assert.equal(await page.locator('polyline[data-channel]').count(),4);const before=await page.locator('polyline[data-channel="1"]').getAttribute('points');await page.locator('[data-zoom=in]').click();assert((await page.locator('.atlas-status').innerText()).includes('2×'));assert.notEqual(await page.locator('polyline[data-channel="1"]').getAttribute('points'),before);await page.locator('input[value="1"]').uncheck();assert.equal(await page.locator('polyline[data-channel]').count(),3);await page.locator('[data-reset]').click();assert.equal(await page.locator('polyline[data-channel]').count(),4);assert((await page.locator('.atlas-status').innerText()).includes('1×'));assert((await page.locator('main').innerText()).includes('非患者记录'))});
await test('Atlas keyboard control',async()=>{await page.locator('[data-zoom=in]').focus();await page.keyboard.press('Enter');assert((await page.locator('.atlas-status').innerText()).includes('2×'))});
await test('404 returns actual 404',async()=>{const r=await go('this-page-does-not-exist/');assert.equal(r.status(),404);assert((await page.locator('h1').innerText()).includes('这条路径'))});
await test('Mobile menu and navigation',async()=>{await page.setViewportSize({width:390,height:844});await go();await page.locator('.mobile-nav summary').click();await page.locator('.mobile-nav nav a').filter({hasText:'注册研究'}).click();assert(page.url().includes('/trials/'));assert.equal(await page.locator('h1').count(),1)});
const routes=['','library/','library/40348201/','trials/nct01390220/','atlas/asynchronous/','team/','research/phenotypes/','methods/slow-potential/'];
for(const width of [1440,768,390])for(const route of routes){await test(`${width}px no overflow ${route||'home'}`,async()=>{await page.setViewportSize({width,height:width===390?844:1000});await go(route);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.equal(await page.locator('h1').count(),1);assert(await page.locator('body').evaluate(el=>getComputedStyle(el).backgroundColor!=='rgba(0, 0, 0, 0)'));if(width!==768)await page.screenshot({path:`${out}/${width}-${route.replaceAll('/','-')||'home'}.png`,fullPage:true});})}
await test('All generated pages respond with a single heading',async()=>{const html=[];function walk(d){for(const e of fs.readdirSync(d,{withFileTypes:true})){const p=path.join(d,e.name);if(e.isDirectory())walk(p);else if(p.endsWith('index.html'))html.push(path.relative('dist',p).replaceAll('\\','/').replace(/index\.html$/,''));}}walk('dist');for(const route of html){const response=await go(route);assert.equal(response.status(),200,route);assert.equal(await page.locator('h1').count(),1,route);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),route);const broken=await page.locator('img').evaluateAll(imgs=>imgs.filter(img=>!img.complete||img.naturalWidth===0).length);assert.equal(broken,0,route)}});
await test('No JavaScript errors',async()=>assert.deepEqual(errors,[]));
fs.writeFileSync('docs/browser-results.json',JSON.stringify({base,checkedAt:new Date().toISOString(),results,errors},null,2));await browser.close();console.log(`RESULT ${results.filter(r=>r.pass).length}/${results.length} passed`);if(results.some(r=>!r.pass))process.exit(1);
